# Site settings
title: Tiangang Cui
email: myfirstname<dot>mylastname<at>monash.edu
description: > # this means to ignore newlines until "baseurl:"
  Inverse problem, Data Assimilation, Bayesian inference, Uncertainty Quantification, Machine Learning, Markov chain Monte Carlo, Subsurface Modeling
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fastfins.org" # the base hostname & protocol for your site
github_username:  tcui001
twitter_username: 

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
